### ISSUE TITLE
Taunt issue

### ISSUE THREAD

**Issue by SpLinTRTV** [gogozooom/Hide-and-Seek-LC-#4]
Hi ! So i tried your mod with friends and we have a probleme where there is one taunt of each used. Like for the lil taunt only the MGS sound is used and if i remove it it will use the next one wich is "bababooey" it always take the one on the top of the list depending on taunt, bigboi or megaboi. To add to that sometimes, when we are 3 or more some of us can't hear the taunt others do. Thanks in advance.

**Comment by gogozooom** [comment]
I'm having trouble understanding the circumstances causing the issue.
Are you talking about changing the mp3 files in the sounds folder?
![image](https://github.com/user-attachments/assets/1b837ef8-e9e9-4130-8079-34d1ea88ff87)
Which then causes inconsistencies across some clients?

**Comment by SpLinTRTV** [comment]
I wasn't clear enough sorry. I means that when taunting, for the 3 type of taunt (lilboi, bigboi and megaboi) the game/mod will only use the same audio (depending on the type). For exemple, while doing a lilboi only the metal gear solid audio (Taunt-ah.wav) is played. For bigboi it's the amongus one only (BigBoi-amongus.wav) and for the megaboi its the broken table one (MegaBoi-brokenTable.wav). There is no randomness cause it never use the other audio, it take the first audio in alphabetical order, so if I delete the Taunt-ah.wav and reload my game it will use the next one wich is Taunt-bababooey.wav. I tried with only installing your mod only and using a fresh save. Reinstalling the game and r2 and nothing worked.

And for the second point sometimes the taunt isn't heard by some players. Like, as host I most likely will hear every players taunt but some of them won't hear when I taunt or when another player do (its not always the same player that will hear or not, its totally random we are playing at max 4 players). Again, we did test it out with your mod installed only ect...

Hope I made myself more clear, English isn't my first language so I'm still struggling to use the correct words.

**Comment by ZigzagAwaka** [comment]
Oh boy seriously there is multiple taunts from each category ?? I never knew lmao
Yeah i can confirm that only the first one is used, since... i didn't even know other existed ah ah

**Comment by ZigzagAwaka** [comment]
Try getting LCMaxSoundFix mod or EnemySoundFix or any other vanilla audio fix mod to try to fix other players can't hear sound, i personnaly use them and i don't have any issue with taunt audio @SpLinTRTV

**Comment by gogozooom** [comment]
I have changed how the network request is handled for sending the taunt used from the host to the clients. This should fix some issues and hopefully your issue too. You can play with these changes on the new v1.4.0 update!
(Re-open if there are some how still problems)

**Comment by SpLinTRTV** [comment]
So I tried it out, solo and with a friends. I can see in the termianl that it is actually picking different sounds but its not playing in game. There is an error (multiple). I gave you my log so it might be easier for you to understand what went wrong. Maybe its just because of the v65 of lethal and nothing more.
[LogOutput.log](https://github.com/user-attachments/files/17506805/LogOutput.log)

**Comment by gogozooom** [comment]
Ah I see... An oversight on my part. I will work on a patch as soon as I get home!

**Comment by SpLinTRTV** [comment]
> Ah I see... An oversight on my part. I will work on a patch as soon as I get home!

Nice thanks ! You are the best !

**Comment by ZigzagAwaka** [comment]
Hi, i saw the 1.4.1 release that fixed this issue but there is some strange things with this latest update, mainly Abilities.cfg is gone and InputUtils dependency is removed from the manifest, I think you uploaded the wrong package @gogozooom

**Comment by gogozooom** [comment]
The Abilities.cfg automatically is generated once the mod is loaded for the first time. However yes, the InputUtils dependency is missing, I have miss matched the manifest.json, I will send a small patch to the Thunderstore.

**Comment by ZigzagAwaka** [comment]
Nice, thanks

**Comment by SpLinTRTV** [comment]
Everything seems to work perfectly. Thanks again !
